project:
  type: book
  output-dir: _output
  execute-dir: project # This forces all paths to start at your project root
  
book:
  title: "Risk Analysis"
  author: "Pairote Satiracoo"
  chapters:
    - index.qmd  
    - chapters/01_Loss_Distributions.qmd


format:
  html:
    toc: true
    number-sections: true
    number-depth: 2
    code-fold: true

  pdf:
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 2
    colorlinks: true
    geometry:
      - margin=1in
      
execute:
  echo: true
  warning: false
  message: false

editor: source